In [1]:
import numpy as np

## Membuat Array


* array

In [4]:
arr = np.array([1,2,3,4])
arrr = [1,2,3,4]

print(arr * 2)
print(arrr * 2)

[2 4 6 8]
[1, 2, 3, 4, 1, 2, 3, 4]


* np.zeros(), np.ones(), np.full() 
* digunakan untuk mengisi nilai default

In [17]:
# Membuat array berisi nol
arr_zeros = np.zeros(5)
print(f"Membuat array berisi nol {arr_zeros}")

arr_ones = np.ones((2,4))
print(f" membuat array berisi default 1 {arr_ones}")

# memnuat array 2d berisi angka tertentu
arr_full = np.full((3,3), 9)
print(arr_full)

Membuat array berisi nol [0. 0. 0. 0. 0.]
 membuat array berisi default 1 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[9 9 9]
 [9 9 9]
 [9 9 9]]


* np.random.rand(), np.random.randint()

In [ ]:
arr_rand = np.random.rand(3)
print(f"array random float {arr_rand}")

# Angka bulat random antara 1–10
arr_randint = np.random.randint(1, 10, size=1)
print(arr_randint) 

array random float [0.3132218  0.47363124 0.77152897]
[2]


In [29]:
a = np.array([1,2,3])
b = np.array([
    [123], [123]
])
c = np.array([
    [
        [1,2,3],
        [3,4,3]
    ],
    [
        [5,6,3],
        [7,8,3]
    ]
    ])  # 3D

print(c)

[[[1 2 3]
  [3 4 3]]

 [[5 6 3]
  [7 8 3]]]


In [30]:
print(c.shape)

(2, 2, 3)
